# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: BannerData.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'BannerData.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x42\x61nnerData.proto\"I\n\x0bRootMessage\x12\x1d\n\x07\x62\x61nners\x18\x01 \x03(\x0b\x32\x0c.BannerGroup\x12\x1b\n\x06\x65vents\x18\x02 \x03(\x0b\x32\x0b.EventGroup\",\n\x0b\x42\x61nnerGroup\x12\x1d\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x0c.BannerEntry\"\xe3\x01\n\x0b\x42\x61nnerEntry\x12\x0e\n\x06region\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\x05\x12\r\n\x05title\x18\x03 \x01(\t\x12\x11\n\timage_url\x18\x05 \x01(\t\x12\x13\n\x0b\x61\x63tion_link\x18\x08 \x01(\t\x12\x12\n\nstart_time\x18\n \x01(\x03\x12\x10\n\x08\x65nd_time\x18\x0b \x01(\x03\x12\x0f\n\x07\x63ountry\x18\x0c \x01(\t\x12\x13\n\x0b\x63\x61mpaign_id\x18\r \x01(\x05\x12\x10\n\x08priority\x18\x13 \x01(\x05\x12\x11\n\taction_id\x18\x14 \x01(\t\x12\x0e\n\x06layout\x18\x16 \x01(\x05\"*\n\nEventGroup\x12\x1c\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x0b.EventEntry\"\xdd\x02\n\nEventEntry\x12\x0f\n\x07\x63ountry\x18\x01 \x01(\t\x12\x0e\n\x06region\x18\x02 \x01(\t\x12\x10\n\x08\x65vent_id\x18\x03 \x01(\x05\x12\r\n\x05title\x18\x04 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x05 \x01(\x05\x12\x12\n\nstart_time\x18\x06 \x01(\x03\x12\x10\n\x08\x65nd_time\x18\x07 \x01(\x03\x12\r\n\x05group\x18\t \x01(\x05\x12\x12\n\x08group_id\x18\n \x01(\tH\x00\x12#\n\x0especial_sub_10\x18\x15 \x01(\x0b\x32\t.SubFieldH\x00\x12\x14\n\ngroup_id_2\x18\x0c \x01(\tH\x01\x12#\n\x0especial_sub_12\x18\x16 \x01(\x0b\x32\t.SubFieldH\x01\x12\x11\n\timage_url\x18\x0e \x01(\t\x12\x0e\n\x06layout\x18\x0f \x01(\x05\x12\r\n\x05width\x18\x11 \x01(\x05\x42\x0e\n\x0cspecial_infoB\x10\n\x0especial_info_2\"\x19\n\x08SubField\x12\r\n\x05value\x18\x07 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BannerData_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROOTMESSAGE']._serialized_start=20
  _globals['_ROOTMESSAGE']._serialized_end=93
  _globals['_BANNERGROUP']._serialized_start=95
  _globals['_BANNERGROUP']._serialized_end=139
  _globals['_BANNERENTRY']._serialized_start=142
  _globals['_BANNERENTRY']._serialized_end=369
  _globals['_EVENTGROUP']._serialized_start=371
  _globals['_EVENTGROUP']._serialized_end=413
  _globals['_EVENTENTRY']._serialized_start=416
  _globals['_EVENTENTRY']._serialized_end=765
  _globals['_SUBFIELD']._serialized_start=767
  _globals['_SUBFIELD']._serialized_end=792
# @@protoc_insertion_point(module_scope)
